<a href="https://colab.research.google.com/github/armonperez/PyTorch-Studies-/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

Resource video : https://www.youtube.com/watch?v=V_xro1bcAuA

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors


### Creating tensors

Pytorch tensors are created using `torch.tensor()` -= https://pytorch.org/docs/stable/tensors.html





In [3]:
#Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
#vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
MAX = torch.tensor([[[[5,6,7,7],
                     [7,8,9,3],
                    [3,2,1,4],
                   ]]])
MAX

tensor([[[[5, 6, 7, 7],
          [7, 8, 9, 3],
          [3, 2, 1, 4]]]])

In [ ]:
MAX.ndim

4

In [ ]:
MAX.shape

torch.Size([1, 1, 3, 4])

##Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that
they start  with tensors full of random numbers and then adjust those random numbers to better represent the data.



```
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers```




In [4]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9879, 0.0210, 0.3738, 0.7410],
        [0.6944, 0.2326, 0.0569, 0.3447],
        [0.2934, 0.7813, 0.5310, 0.2563]])

In [8]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size= (224,224, 3)) #height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [11]:
#Creating my own random tensor
random_tensor  = torch.rand (2, 4, 5)
random_tensor

tensor([[[0.7684, 0.7898, 0.1956, 0.5301, 0.0034],
         [0.1766, 0.1693, 0.6901, 0.1987, 0.2549],
         [0.5698, 0.1790, 0.9315, 0.4541, 0.7918],
         [0.9894, 0.0500, 0.3045, 0.5126, 0.8594]],

        [[0.6524, 0.9899, 0.1037, 0.0842, 0.5331],
         [0.0834, 0.3266, 0.5134, 0.9806, 0.8929],
         [0.3788, 0.5117, 0.1387, 0.5808, 0.7876],
         [0.8659, 0.3050, 0.8263, 0.8208, 0.7300]]])

In [12]:
random_tensor.ndim

3

In [13]:
random_tensor.shape

torch.Size([2, 4, 5])

## Zeros and ones

In [14]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
#Create a tensor od all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

In [19]:
#Created my own
zeros = torch.zeros(1,4,3)
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

##Creating a range of tensors and tensors-like

In [27]:
# use torch.range(). or use torch,arange() if get a deprecated message
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Creating tensors like
ten_zeros= torch.zeros_like (input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
#create my own
five_to_twenty = torch.arange(start= 5, end= 21, step = 5)
five_to_twenty

tensor([ 5, 10, 15, 20])

In [34]:
four_zeros = torch.zeros_like (input = five_to_twenty)
four_zeros

tensor([0, 0, 0, 0])

##Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [41]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #What datatype is the tensor (e.g. float32 or float16)
                               device=None, #What device is your tensor on
                               requires_grad =False) #Wheather or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [42]:
float_32_tensor.dtype

torch.float32

In [43]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [47]:
#Practice

complex_tensor = torch.tensor([5.9,6.0,2.0],
                              dtype = torch.float64,
                              device = None,
                              requires_grad = False)
complex_tensor

tensor([5.9000, 6.0000, 2.0000], dtype=torch.float64)

In [48]:
complex_tensor.dtype

torch.float64

In [50]:
#Multiplying two tensors together performs the operations and takes on the more precise dtype
complex_tensor * float_32_tensor

tensor([17.7000, 36.0000, 18.0000], dtype=torch.float64)