<a href="https://colab.research.google.com/github/armonperez/PyTorch-Studies-/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

Resource video : https://www.youtube.com/watch?v=V_xro1bcAuA

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors


### Creating tensors

Pytorch tensors are created using `torch.tensor()` -= https://pytorch.org/docs/stable/tensors.html





In [2]:
#Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
#vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [16]:
MAX = torch.tensor([[[[5,6,7,7],
                     [7,8,9,3],
                    [3,2,1,4],
                   ]]])
MAX

tensor([[[[5, 6, 7, 7],
          [7, 8, 9, 3],
          [3, 2, 1, 4]]]])

In [17]:
MAX.ndim

4

In [18]:
MAX.shape

torch.Size([1, 1, 3, 4])

##Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that
they start  with tensors full of random numbers and then adjust those random numbers to better represent the data.



```
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers```




In [19]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7626, 0.7785, 0.5931, 0.9083],
        [0.6484, 0.2387, 0.5412, 0.9893],
        [0.7395, 0.1693, 0.9834, 0.8462]])

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size= (224,224, 3)) #height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
#Creating my own random tensor
random_tensor  = torch.rand (2, 4, 5)
random_tensor

tensor([[[0.4544, 0.7864, 0.6063, 0.5620, 0.7871],
         [0.6019, 0.0042, 0.6706, 0.4350, 0.3459],
         [0.7643, 0.4557, 0.6213, 0.8480, 0.8537],
         [0.9747, 0.4515, 0.9494, 0.3284, 0.7122]],

        [[0.0637, 0.6660, 0.2484, 0.8440, 0.2162],
         [0.6445, 0.5898, 0.2029, 0.5958, 0.1835],
         [0.2020, 0.0535, 0.5440, 0.3327, 0.5137],
         [0.1686, 0.5702, 0.6004, 0.4521, 0.5760]]])

In [22]:
random_tensor.ndim

3

In [23]:
random_tensor.shape

torch.Size([2, 4, 5])

## Zeros and ones

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
#Create a tensor od all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [27]:
#Created my own
zeros = torch.zeros(1,4,3)
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

##Creating a range of tensors and tensors-like

In [28]:
# use torch.range(). or use torch,arange() if get a deprecated message
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Creating tensors like
ten_zeros= torch.zeros_like (input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
#create my own
five_to_twenty = torch.arange(start= 5, end= 21, step = 5)
five_to_twenty

tensor([ 5, 10, 15, 20])

In [31]:
four_zeros = torch.zeros_like (input = five_to_twenty)
four_zeros

tensor([0, 0, 0, 0])

##Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #What datatype is the tensor (e.g. float32 or float16)
                               device=None, #What device is your tensor on
                               requires_grad =False) #Wheather or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
#Practice

complex_tensor = torch.tensor([5.9,6.0,2.0],
                              dtype = torch.complex128,
                              device = None,
                              requires_grad = False)
complex_tensor

tensor([5.9000+0.j, 6.0000+0.j, 2.0000+0.j], dtype=torch.complex128)

In [36]:
complex_tensor.dtype

torch.complex128

In [37]:
#Multiplying two tensors together performs the operations and takes on the more precise dtype
complex_tensor * float_32_tensor

tensor([17.7000+0.j, 36.0000+0.j, 18.0000+0.j], dtype=torch.complex128)

### Getting information from tensors (tensor attribute)


1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [38]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0605, 0.4490, 0.5344, 0.3179],
        [0.3206, 0.8286, 0.2307, 0.3279],
        [0.6127, 0.5449, 0.3122, 0.2714]])

In [39]:
# Find out details about some tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0605, 0.4490, 0.5344, 0.3179],
        [0.3206, 0.8286, 0.2307, 0.3279],
        [0.6127, 0.5449, 0.3122, 0.2714]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [40]:
#practice
#change the dtype and the device

my_tensor = torch.rand([2,2],
                       dtype = torch.float16,
                      device = torch.device('cpu'))
my_tensor

tensor([[0.1079, 0.3652],
        [0.9058, 0.4985]], dtype=torch.float16)

In [41]:
print(my_tensor)
print(f"Datatype of tensor : {my_tensor.dtype}")
print(f"Shape of tensor : {my_tensor.shape}")
print(f"Device tensor is on : {my_tensor.device}")


tensor([[0.1079, 0.3652],
        [0.9058, 0.4985]], dtype=torch.float16)
Datatype of tensor : torch.float16
Shape of tensor : torch.Size([2, 2])
Device tensor is on : cpu


### Manipulating Tensors (tensor operations)





Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [42]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [43]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
# Subtrtact 10
tensor - 10

tensor([-9, -8, -7])

In [46]:
# Try out PyTorch in-built finctions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [47]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of preforming multiplication in neural networks and deep learning:
  1. Element-wise multiplication
  2. Matrix multiplication (dot product)

  More information of multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

  There are two main rules that performing matrix multiplication needs to satisfy:
  1. The **inner dimensions** must match:
  * `(3,2) @ (3,2)` won't work
  * `(2,3) @ (3,2)` will work
  * `(3,2) @ (2,3)` will work

  2. The resulting matrix has the shape of the **outer dimensions**
  * `(2,3) @ (3,2)` -> `(2,2)`
  * `(3,2) @ (2,3)` -> `(3,3)`

  For a Visual: http://matrixmultiplication.xyz/

In [48]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[2.9023, 2.8305, 4.0545],
        [1.8716, 1.8534, 3.0442],
        [1.9849, 1.6265, 3.1818]])

In [49]:
# Element wise multiplication
print (tensor, " *",  tensor)
print (f"Equals: {tensor * tensor}")

tensor([1, 2, 3])  * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [50]:
#. Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [51]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [52]:
# Compare the time of a for loop and the vectorized torch function
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.48 ms, sys: 0 ns, total: 1.48 ms
Wall time: 13.3 ms


In [53]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 66 µs, sys: 8 µs, total: 74 µs
Wall time: 78.7 µs


tensor(14)

In [54]:
#practice
my_tensor = torch.tensor ([5,6,7],
                        dtype = torch.float16)

my_tensor

tensor([5., 6., 7.], dtype=torch.float16)

In [55]:
#practice
Mt_tensor2 = torch.tensor ([2,2,2],
                         dtype = torch.float16)
Mt_tensor2

tensor([2., 2., 2.], dtype=torch.float16)

In [56]:
#practice
final_tensor = torch.matmul(my_tensor, Mt_tensor2)
print(f"the device the tensor is on: {final_tensor.device}")
print(f"the dtype of the tensor :    {final_tensor.dtype}")
print(f"the shape of the tensor :    {final_tensor.shape}")


the device the tensor is on: cpu
the dtype of the tensor :    torch.float16
the shape of the tensor :    torch.Size([])


### One of the most common errors in deep learning: shape errors

In [58]:
# Shapes for matrix multiplication


tensor_A = torch.tensor ([[1,2],
                          [3,4],
                          [5,6]])

tensor_B = torch.tensor ([[7,10],
                          [8,11],
                          [9,12]])

torch.matmul(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

# will give an error because inner dimensions do not match.

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
tensor_B, tensor_B.shape

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match ")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

#Get a shape of (3,3) because that is the outer dim of the tensors

In [ ]:
#Practice example

prac1= torch.tensor ([[1,2,3],
                     [1,2,3],
                     [1,2,3]])

prac2= torch.tensor ([[3,4,5],
                      [1,2,3],
                      [6,1,8],
                      [9,2,3]])

torch.matmul(prac1,prac2)

#This will give an error because inner dimensions do not match. (3, 3 and 4, 3) it needs to be (3,3 and 3,4 in order to work)
#Transpose prac2 tensor would allow matrix multiplication to work

In [ ]:
# Transpose and multiply
print(f"original shape: prac1 = {prac1.shape}, prac2 = {prac2.shape}")
print(f"New shape : prac1 = {prac1.shape} (same shape as above), prac2.T = {prac2.T.shape}")
print(f"Multiplying: {prac1.shape} @ {prac2.T.shape} <- inner dimensions must match ")
print("Output:\n")
output = torch.matmul(prac1, prac2.T)
print(output)
print(f"\nOutput shape: {output.shape}")

In [ ]:
# More Practice

Prac3 = torch.rand(2,3)

Prac4 = torch.rand(2,4)


print(f"Original shape : Prac3 = {Prac3.shape}, Prac4 = {Prac4.shape}")
print(f"The original will cause an error becasue the inner dimenstions dont match")
print(f"{Prac3.shape} , {Prac4.shape}")
print(" ")
print(f"New shape : Prac3 = {Prac3.T.shape}, Prac4 = {Prac4.shape}")
print(f"Multiplying : Prac3.T @ Prac4 <- inner dimenstions match")
print("Output:\n")
output = torch.matmul(Prac3.T, Prac4)
print(output)
print(f"\nOutput shape: {output.shape}")




## Finding the min, max, mean ,sum , etc (tensor aggregation)

In [ ]:
# Create a tensor

x = torch.arange(1 , 100 , 10)

x, x.dtype

In [ ]:
# Find the min
torch.min(x), x.min()

In [ ]:
# Find the max
torch.max(x), x.max()

In [ ]:
# Find the mean  - note: the torch.mean() function requires a float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
# Find the sum
torch.sum(x), x.sum()

## Finding the positional min and max

In [ ]:
x

In [ ]:
# FInd the postition in tensor that has the minium value with argmin() -> returns index position of target tensor where the minimum value occurs
#index
x.argmin()

In [ ]:
# Find the position in tensor that has the max value with argmax()
#index

x.argmax()

In [ ]:
x[9]

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimenstion to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [61]:
# Let's create a tensor
import torch

x= torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [62]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
# changed the first element of z
z[: , 0] =5
z, x

In [87]:
# Stack tenosrs on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [96]:
x_vstacked = torch.vstack([x, x, x, x])
x_vstacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [97]:
x_Hstacked = torch.hstack([x, x, x, x])
x_Hstacked

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [102]:
# torch.squeeze() -> Removes all single dimenstions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")



Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [110]:
# torch.unsqueeze() = adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimenstion with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [111]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand (size = (224, 224, 3)) #[height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute (2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [122]:

x_original[0,0,0] = 8
x_original[0,0,0], x_permuted[0,0,0]



(tensor(8.), tensor(8.))

## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [125]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape (1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [126]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [129]:
# Lets index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [131]:
# Lets index on the most inner bracket
x[0][2][2]

tensor(9)

In [132]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]


tensor([[1, 2, 3]])

In [133]:
# Get all values of 0th and 1st dimensions but only index 1 of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [136]:
 # Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
 x[0,1,1]

tensor(5)

In [137]:
# Get index 0 of 0th and 1st dimenstion and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [145]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [146]:
# Index on x to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [153]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [154]:
# Change the value of array, what will thsi do to `tensor` ?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [155]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [157]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility  (trying to take random out of random)

In short how a neural network learns:

`start with randome numbers-> tensor operations ->update random numbers to try and
make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [250]:
import torch

# Create two random tensor

random_tensor_A = torch.rand (3,4)
random_tensor_B = torch.rand (3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0017, 0.0886, 0.6913, 0.4050],
        [0.8769, 0.2081, 0.4743, 0.4469],
        [0.2105, 0.1895, 0.6027, 0.9545]])
tensor([[0.8306, 0.5254, 0.5778, 0.2606],
        [0.7210, 0.2865, 0.3419, 0.3041],
        [0.3103, 0.8788, 0.9445, 0.3537]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [260]:
# Let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility
* https://pytorch.org/docs/stable/notes/randomness.html
*https://en.wikipedia.org/wiki/Random_seed
