<a href="https://colab.research.google.com/github/armonperez/PyTorch-Studies-/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

Resource video : https://www.youtube.com/watch?v=V_xro1bcAuA

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors


### Creating tensors

Pytorch tensors are created using `torch.tensor()` -= https://pytorch.org/docs/stable/tensors.html





In [2]:
#Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
#vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [16]:
MAX = torch.tensor([[[[5,6,7,7],
                     [7,8,9,3],
                    [3,2,1,4],
                   ]]])
MAX

tensor([[[[5, 6, 7, 7],
          [7, 8, 9, 3],
          [3, 2, 1, 4]]]])

In [17]:
MAX.ndim

4

In [18]:
MAX.shape

torch.Size([1, 1, 3, 4])

##Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that
they start  with tensors full of random numbers and then adjust those random numbers to better represent the data.



```
Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers```




In [19]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6231, 0.9451, 0.6607, 0.9325],
        [0.3059, 0.9683, 0.3154, 0.3721],
        [0.2100, 0.1176, 0.0509, 0.7890]])

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size= (224,224, 3)) #height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
#Creating my own random tensor
random_tensor  = torch.rand (2, 4, 5)
random_tensor

tensor([[[0.1298, 0.2238, 0.3487, 0.7271, 0.1846],
         [0.1434, 0.0178, 0.7764, 0.0327, 0.2045],
         [0.0958, 0.1465, 0.9142, 0.1516, 0.7792],
         [0.6554, 0.9434, 0.4342, 0.7152, 0.8260]],

        [[0.0827, 0.8269, 0.8793, 0.6755, 0.2133],
         [0.5080, 0.1797, 0.5924, 0.8049, 0.0746],
         [0.9400, 0.7264, 0.7611, 0.3744, 0.6602],
         [0.1388, 0.1574, 0.0264, 0.7727, 0.7240]]])

In [22]:
random_tensor.ndim

3

In [23]:
random_tensor.shape

torch.Size([2, 4, 5])

## Zeros and ones

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
#Create a tensor od all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [27]:
#Created my own
zeros = torch.zeros(1,4,3)
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

##Creating a range of tensors and tensors-like

In [28]:
# use torch.range(). or use torch,arange() if get a deprecated message
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Creating tensors like
ten_zeros= torch.zeros_like (input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
#create my own
five_to_twenty = torch.arange(start= 5, end= 21, step = 5)
five_to_twenty

tensor([ 5, 10, 15, 20])

In [31]:
four_zeros = torch.zeros_like (input = five_to_twenty)
four_zeros

tensor([0, 0, 0, 0])

##Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #What datatype is the tensor (e.g. float32 or float16)
                               device=None, #What device is your tensor on
                               requires_grad =False) #Wheather or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
#Practice

complex_tensor = torch.tensor([5.9,6.0,2.0],
                              dtype = torch.complex128,
                              device = None,
                              requires_grad = False)
complex_tensor

tensor([5.9000+0.j, 6.0000+0.j, 2.0000+0.j], dtype=torch.complex128)

In [36]:
complex_tensor.dtype

torch.complex128

In [37]:
#Multiplying two tensors together performs the operations and takes on the more precise dtype
complex_tensor * float_32_tensor

tensor([17.7000+0.j, 36.0000+0.j, 18.0000+0.j], dtype=torch.complex128)

### Getting information from tensors (tensor attribute)


1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [38]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2270, 0.1611, 0.0111, 0.6904],
        [0.1793, 0.9749, 0.9605, 0.8393],
        [0.8348, 0.7290, 0.2222, 0.9468]])

In [39]:
# Find out details about some tensor

print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2270, 0.1611, 0.0111, 0.6904],
        [0.1793, 0.9749, 0.9605, 0.8393],
        [0.8348, 0.7290, 0.2222, 0.9468]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [42]:
#practice
#change the dtype and the device

my_tensor = torch.rand([2,2],
                       dtype = torch.float16,
                      device = torch.device('cpu'))
my_tensor

tensor([[0.0381, 0.2646],
        [0.8770, 0.6733]], dtype=torch.float16)

In [44]:
print(my_tensor)
print(f"Datatype of tensor : {my_tensor.dtype}")
print(f"Shape of tensor : {my_tensor.shape}")
print(f"Device tensor is on : {my_tensor.device}")


tensor([[0.0381, 0.2646],
        [0.8770, 0.6733]], dtype=torch.float16)
Datatype of tensor : torch.float16
Shape of tensor : torch.Size([2, 2])
Device tensor is on : cpu


### Manipulating Tensors (tensor operations)





Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [45]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [46]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [47]:
tensor

tensor([1, 2, 3])

In [55]:
# Subtrtact 10
tensor - 10

tensor([-9, -8, -7])

In [48]:
# Try out PyTorch in-built finctions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [49]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of preforming multiplication in neural networks and deep learning:
  1. Element-wise multiplication
  2. Matrix multiplication (dot product)

  More information of multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [50]:
# Element wise multiplication
print (tensor, " *",  tensor)
print (f"Equals: {tensor * tensor}")

tensor([1, 2, 3])  * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [51]:
#. Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [52]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [53]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.21 ms, sys: 30 µs, total: 2.24 ms
Wall time: 2.1 ms


In [54]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 122 µs, total: 122 µs
Wall time: 144 µs


tensor(14)